### ISSUE TITLE
No asciidoc installed

### ISSUE THREAD

**Issue by abradshaw** [publysher/docker-hugo#13]
Hugo sites that use asciidoc dont get rendered as the container doesnt seem to have asciidoc

**Comment by titpetric** [comment]
@abradshaw can you give some more info about this:

1. which sites use asciidoc,
2. do you have a way to replicate this in a container?

I'll gladly submit a PR, if you can give me a case to test against.

**Comment by abradshaw** [comment]
Hi
So Hugo lets you write your websites "source" pages in either Markdown (the default) or in asciidoc 

Gitlab also let you host the site on their servers - "gitlab pages", so the workflow is that you have hugo installed locally on your laptop/desktop, you create a source page or post in asciidoc and then you upload it to your gitlab account (git push) that will pull this container and render the source pages into html and then transfer the rendered pages to their ow hosting service

Its described here https://gohugo.io/tutorials/hosting-on-gitlab/ 

So I think the first thing to do it to just try adding the asciidoc package to the docker container 

Thanks for your help

**Comment by titpetric** [comment]
@abradshaw sure, that's what I'd like to *test*, which means I have to produce an asciidoc post first, instead of blindly adding a package to the Dockerfile :). I suppose you have an example of such a post at hand? If you can add it as a code block (or on a service like pastebin), you'd be making my work a bit easier :)

**Comment by abradshaw** [comment]
Yes of course, sorry 

https://da.gd/G61NJ
